server:
  address: 127.0.0.1
  port: 8089
spring:
  application:
    name: mybatis-tkmapper
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
         maximum-pool-size: 100
         minimum-idle: 10
         register-mbeans: false
         pool-name: 光连接池
         connection-test-query: select 1
         connection-timeout: 1000
         initialization-fail-fast: true
         validation-timeout: 6000
management:
  cloudfoundry:
    enabled: true
  security:
    enabled: false
endpoints:
  shutdown:
    #开启shutdown端点
    enabled: true
mybatis:
  configuration:
    interceptors:  com.github.pagehelper.PageInterceptor
    jdbc-type-for-null: other
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: true
pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
